#!/usr/bin/python3

from biblioteca import Biblioteca
"""
livro1 = Livro("Aguape", "Pe. Marcelo Rossi", 2015)
livro2 = Livro("O pequeno principe", "Antoine de Saint-Exupéry","1943")

print(livro1.info_livro())
print(livro2.info_livro())"""

a = Biblioteca()

a.adicionar_livro("Aguape", "Pe. Marcelo Rossi", 2015)
a.adicionar_livro("Metanoia", "Pe. Marcelo Rossi", 2018)
a.adicionar_livro("O Pequeno Príncipe", "Antoine de Saint-Exupéry", 1943)
a.adicionar_livro("Voo Noturno", "Antoine de Saint-Exupéry", 1931)
a.adicionar_livro("Dom Casmurro", "Machado de Assis", 1899)
a.adicionar_livro("Memórias Póstumas de Brás Cubas", "Machado de Assis", 1881)
a.adicionar_livro("Quincas Borba", "Machado de Assis", 1891)
a.adicionar_livro("1984", "George Orwell", 1949)
a.adicionar_livro("A Revolução dos Bichos", "George Orwell", 1945)
a.adicionar_livro("O Senhor dos Anéis: A Sociedade do Anel", "J.R.R. Tolkien", 1954)
a.adicionar_livro("O Senhor dos Anéis: As Duas Torres", "J.R.R. Tolkien", 1954)
a.adicionar_livro("O Senhor dos Anéis: O Retorno do Rei", "J.R.R. Tolkien", 1955)
a.adicionar_livro("O Hobbit", "J.R.R. Tolkien", 1937)
a.adicionar_livro("Harry Potter e a Pedra Filosofal", "J.K. Rowling", 1997)
a.adicionar_livro("Harry Potter e a Câmara Secreta", "J.K. Rowling", 1998)
a.adicionar_livro("Harry Potter e o Prisioneiro de Azkaban", "J.K. Rowling", 1999)
a.adicionar_livro("Harry Potter e o Cálice de Fogo", "J.K. Rowling", 2000)
a.adicionar_livro("Orgulho e Preconceito", "Jane Austen", 1813)
a.adicionar_livro("Razão e Sensibilidade", "Jane Austen", 1811)
a.adicionar_livro("Emma", "Jane Austen", 1815)
a.adicionar_livro("O Código Da Vinci", "Dan Brown", 2003)
a.adicionar_livro("Anjos e Demônios", "Dan Brown", 2000)
a.adicionar_livro("Inferno", "Dan Brown", 2013)
a.adicionar_livro("Cem Anos de Solidão", "Gabriel García Márquez", 1967)
a.adicionar_livro("O Amor nos Tempos do Cólera", "Gabriel García Márquez", 1985)
a.adicionar_livro("Crônica de uma Morte Anunciada", "Gabriel García Márquez", 1981)
a.adicionar_livro("O Alquimista", "Paulo Coelho", 1988)
a.adicionar_livro("Brida", "Paulo Coelho", 1990)
a.adicionar_livro("Veronika Decide Morrer", "Paulo Coelho", 1998)
a.adicionar_livro("A Menina que Roubava Livros", "Markus Zusak", 2005)
a.adicionar_livro("Eu Sou o Mensageiro", "Markus Zusak", 2002)
a.adicionar_livro("A Culpa é das Estrelas", "John Green", 2012)
a.adicionar_livro("Quem é Você, Alasca?", "John Green", 2005)
a.adicionar_livro("Cidades de Papel", "John Green", 2008)
a.adicionar_livro("It: A Coisa", "Stephen King", 1986)
a.adicionar_livro("O Iluminado", "Stephen King", 1977)
a.adicionar_livro("Carrie, a Estranha", "Stephen King", 1974)
a.adicionar_livro("Doutor Sono", "Stephen King", 2013)
a.adicionar_livro("O Nome do Vento", "Patrick Rothfuss", 2007)
a.adicionar_livro("O Temor do Sábio", "Patrick Rothfuss", 2011)
a.adicionar_livro("O Diário de Anne Frank", "Anne Frank", 1947)
a.adicionar_livro("Moby Dick", "Herman Melville", 1851)
a.adicionar_livro("Billy Budd, Marinheiro", "Herman Melville", 1924)
a.adicionar_livro("A Metamorfose", "Franz Kafka", 1915)
a.adicionar_livro("O Processo", "Franz Kafka", 1925)
a.adicionar_livro("O Castelo", "Franz Kafka", 1926)
a.adicionar_livro("O Morro dos Ventos Uivantes", "Emily Brontë", 1847)
a.adicionar_livro("Jane Eyre", "Charlotte Brontë", 1847)
a.adicionar_livro("Admirável Mundo Novo", "Aldous Huxley", 1932)
a.adicionar_livro("Contraponto", "Aldous Huxley", 1928)

a.listar_todos()

#a.buscar_por_autor("Stephen King")
